# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DeviceMessages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DeviceMessages.proto',
  package='relay',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x14\x44\x65viceMessages.proto\x12\x05relay\" \n\x10ProvisioningUuid\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"4\n\x11ProvisionEnvelope\x12\x11\n\tpublicKey\x18\x01 \x01(\x0c\x12\x0c\n\x04\x62ody\x18\x02 \x01(\x0c\"i\n\x10ProvisionMessage\x12\x1a\n\x12identityKeyPrivate\x18\x02 \x01(\x0c\x12\x0c\n\x04\x61\x64\x64r\x18\x03 \x01(\t\x12\x18\n\x10provisioningCode\x18\x04 \x01(\t\x12\x11\n\tuserAgent\x18\x05 \x01(\t')
)




_PROVISIONINGUUID = _descriptor.Descriptor(
  name='ProvisioningUuid',
  full_name='relay.ProvisioningUuid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='relay.ProvisioningUuid.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=63,
)


_PROVISIONENVELOPE = _descriptor.Descriptor(
  name='ProvisionEnvelope',
  full_name='relay.ProvisionEnvelope',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='publicKey', full_name='relay.ProvisionEnvelope.publicKey', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='body', full_name='relay.ProvisionEnvelope.body', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=117,
)


_PROVISIONMESSAGE = _descriptor.Descriptor(
  name='ProvisionMessage',
  full_name='relay.ProvisionMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='identityKeyPrivate', full_name='relay.ProvisionMessage.identityKeyPrivate', index=0,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='addr', full_name='relay.ProvisionMessage.addr', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='provisioningCode', full_name='relay.ProvisionMessage.provisioningCode', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='userAgent', full_name='relay.ProvisionMessage.userAgent', index=3,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=224,
)

DESCRIPTOR.message_types_by_name['ProvisioningUuid'] = _PROVISIONINGUUID
DESCRIPTOR.message_types_by_name['ProvisionEnvelope'] = _PROVISIONENVELOPE
DESCRIPTOR.message_types_by_name['ProvisionMessage'] = _PROVISIONMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProvisioningUuid = _reflection.GeneratedProtocolMessageType('ProvisioningUuid', (_message.Message,), dict(
  DESCRIPTOR = _PROVISIONINGUUID,
  __module__ = 'DeviceMessages_pb2'
  # @@protoc_insertion_point(class_scope:relay.ProvisioningUuid)
  ))
_sym_db.RegisterMessage(ProvisioningUuid)

ProvisionEnvelope = _reflection.GeneratedProtocolMessageType('ProvisionEnvelope', (_message.Message,), dict(
  DESCRIPTOR = _PROVISIONENVELOPE,
  __module__ = 'DeviceMessages_pb2'
  # @@protoc_insertion_point(class_scope:relay.ProvisionEnvelope)
  ))
_sym_db.RegisterMessage(ProvisionEnvelope)

ProvisionMessage = _reflection.GeneratedProtocolMessageType('ProvisionMessage', (_message.Message,), dict(
  DESCRIPTOR = _PROVISIONMESSAGE,
  __module__ = 'DeviceMessages_pb2'
  # @@protoc_insertion_point(class_scope:relay.ProvisionMessage)
  ))
_sym_db.RegisterMessage(ProvisionMessage)


# @@protoc_insertion_point(module_scope)
