# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SubProtocol.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SubProtocol.proto',
  package='relay',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x11SubProtocol.proto\x12\x05relay\"O\n\x17WebSocketRequestMessage\x12\x0c\n\x04verb\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x0c\n\x04\x62ody\x18\x03 \x01(\x0c\x12\n\n\x02id\x18\x04 \x01(\x04\"U\n\x18WebSocketResponseMessage\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0e\n\x06status\x18\x02 \x01(\r\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x0c\n\x04\x62ody\x18\x04 \x01(\x0c\"\xd2\x01\n\x10WebSocketMessage\x12*\n\x04type\x18\x01 \x01(\x0e\x32\x1c.relay.WebSocketMessage.Type\x12/\n\x07request\x18\x02 \x01(\x0b\x32\x1e.relay.WebSocketRequestMessage\x12\x31\n\x08response\x18\x03 \x01(\x0b\x32\x1f.relay.WebSocketResponseMessage\".\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07REQUEST\x10\x01\x12\x0c\n\x08RESPONSE\x10\x02')
)



_WEBSOCKETMESSAGE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='relay.WebSocketMessage.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REQUEST', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESPONSE', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=361,
  serialized_end=407,
)
_sym_db.RegisterEnumDescriptor(_WEBSOCKETMESSAGE_TYPE)


_WEBSOCKETREQUESTMESSAGE = _descriptor.Descriptor(
  name='WebSocketRequestMessage',
  full_name='relay.WebSocketRequestMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='verb', full_name='relay.WebSocketRequestMessage.verb', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='path', full_name='relay.WebSocketRequestMessage.path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='body', full_name='relay.WebSocketRequestMessage.body', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='relay.WebSocketRequestMessage.id', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=107,
)


_WEBSOCKETRESPONSEMESSAGE = _descriptor.Descriptor(
  name='WebSocketResponseMessage',
  full_name='relay.WebSocketResponseMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='relay.WebSocketResponseMessage.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='relay.WebSocketResponseMessage.status', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='relay.WebSocketResponseMessage.message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='body', full_name='relay.WebSocketResponseMessage.body', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=194,
)


_WEBSOCKETMESSAGE = _descriptor.Descriptor(
  name='WebSocketMessage',
  full_name='relay.WebSocketMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='relay.WebSocketMessage.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request', full_name='relay.WebSocketMessage.request', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='response', full_name='relay.WebSocketMessage.response', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _WEBSOCKETMESSAGE_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=407,
)

_WEBSOCKETMESSAGE.fields_by_name['type'].enum_type = _WEBSOCKETMESSAGE_TYPE
_WEBSOCKETMESSAGE.fields_by_name['request'].message_type = _WEBSOCKETREQUESTMESSAGE
_WEBSOCKETMESSAGE.fields_by_name['response'].message_type = _WEBSOCKETRESPONSEMESSAGE
_WEBSOCKETMESSAGE_TYPE.containing_type = _WEBSOCKETMESSAGE
DESCRIPTOR.message_types_by_name['WebSocketRequestMessage'] = _WEBSOCKETREQUESTMESSAGE
DESCRIPTOR.message_types_by_name['WebSocketResponseMessage'] = _WEBSOCKETRESPONSEMESSAGE
DESCRIPTOR.message_types_by_name['WebSocketMessage'] = _WEBSOCKETMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WebSocketRequestMessage = _reflection.GeneratedProtocolMessageType('WebSocketRequestMessage', (_message.Message,), dict(
  DESCRIPTOR = _WEBSOCKETREQUESTMESSAGE,
  __module__ = 'SubProtocol_pb2'
  # @@protoc_insertion_point(class_scope:relay.WebSocketRequestMessage)
  ))
_sym_db.RegisterMessage(WebSocketRequestMessage)

WebSocketResponseMessage = _reflection.GeneratedProtocolMessageType('WebSocketResponseMessage', (_message.Message,), dict(
  DESCRIPTOR = _WEBSOCKETRESPONSEMESSAGE,
  __module__ = 'SubProtocol_pb2'
  # @@protoc_insertion_point(class_scope:relay.WebSocketResponseMessage)
  ))
_sym_db.RegisterMessage(WebSocketResponseMessage)

WebSocketMessage = _reflection.GeneratedProtocolMessageType('WebSocketMessage', (_message.Message,), dict(
  DESCRIPTOR = _WEBSOCKETMESSAGE,
  __module__ = 'SubProtocol_pb2'
  # @@protoc_insertion_point(class_scope:relay.WebSocketMessage)
  ))
_sym_db.RegisterMessage(WebSocketMessage)


# @@protoc_insertion_point(module_scope)
